"""add_unique_index_and_updated_at_to_transactions

Revision ID: 6223070eec00
Revises: 41371b64d3e7
Create Date: 2026-09-21 02:33:47.998013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6223070eec00'
down_revision: Union[str, Sequence[str], None] = '41371b64d3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_transactions_request_id', 'transactions', ['request_id'], unique=False)
    op.create_unique_constraint('uq_transactions_request_id', 'transactions', ['request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_request_id', 'transactions', type_='unique')
    op.drop_index('ix_transactions_request_id', table_name='transactions')
    op.drop_column('transactions', 'updated_at')
    # ### end Alembic commands ###
